//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentData
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.PoliceStations = new HashSet<PoliceStation>();
            this.Students = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public string DistrictName { get; set; }
        public int StateId { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<PoliceStation> PoliceStations { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
